# Generated by Django 4.2.11 on 2024-03-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Github_url',
            field=models.URLField(null=True),
        ),
    ]
